export function typeToken(px: any): null;
export function spaceToken(px: any): null;
export const APPLY_ORDER: {
    'inject-meta-viewport': number;
    'fix-meta-viewport': number;
    'inject-utopia-scale': number;
    'inject-reduced-motion-guard': number;
    'add-safe-area-inset': number;
    'migrate-px-fonts-to-utopia': number;
    'migrate-px-spacing-to-utopia': number;
    'add-img-aspect-ratio': number;
    'add-remote-img-aspect-ratio': number;
    'fix-fixed-width-overflow': number;
    'fix-element-overflow': number;
    'enforce-touch-target-min': number;
    'tailwind-touch-target': number;
    'tailwind-safe-area': number;
    'truncate-text-overflow': number;
    'tailwind-layout-stack': number;
    'tailwind-form-stack': number;
    'tailwind-sidebar-drawer': number;
    'add-srcset': number;
    'table-to-cards': number;
    'add-pwa-manifest': number;
    'add-apple-touch-icon': number;
    'fix-low-color-contrast': number;
    'add-focus-visible-rules': number;
    'tailwind-nav-hamburger': number;
};
